apiVersion: v1
kind: Service

metadata:
  name: nginx-svc
  namespace: default

spec:
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 80

  selector:
    app: nginx

  type: NodePort