apiVersion: apps/v1 # which api to use for deployment
kind: Deployment # what kind of servece/object you want to create

metadata:
  name: nginx-deployment # naming the deployment
spec:
  selector:
    matchLabels:
      app: nginx # look for this label to match k8 service
  replicas: 3 # create a replica set of this with instances pods
  template:
    metadata:
      labels:
        app: nginx # label connects to the service
    spec:
      containers:
      - name: nginx
        image: benedek4000/nginx-cv:latest
        ports:
        - containerPort: 80