apiVersion: apps/v1 # which api to use for deployment
kind: Deployment # what kind of servece/object you want to create

metadata:
  name: db-deployment # naming the deployment
spec:
  selector:
    matchLabels:
      app: db # look for this label to match k8 service
  replicas: 3 # create a replica set of this with instances pods
  template:
    metadata:
      labels:
        app: db # label connects to the service
    spec:
      containers:
      - name: db
        image: mongo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 27017